use std::collections::HashMap;

pub fn get_project_content(project_id: u32) -> Option<String> {
    let content_map = get_all_project_content();
    content_map.get(&project_id).cloned()
}

fn get_all_project_content() -> HashMap<u32, String> {
    let mut content_map = HashMap::new();
    
    content_map.insert(1, 
        "Our welding capability project represents a groundbreaking approach to automated quality control in industrial welding processes. Utilizing advanced computer vision algorithms, this system can detect microscopic defects, porosity, and structural inconsistencies in real-time during the welding operation. The mobile platform enables field deployment across various industrial settings, from shipbuilding to heavy machinery manufacturing. The system analyzes weld bead geometry, heat distribution patterns, and material flow characteristics to ensure optimal joint integrity. Machine learning models trained on thousands of welding samples can predict potential failure points before they become critical. This technology significantly reduces post-weld inspection time while improving overall quality assurance standards. Implementation includes integration with existing welding equipment through IoT sensors and real-time data streaming capabilities for immediate feedback to operators.".to_string()
    );

    content_map.insert(2,
        "The Clapanator project introduces innovative computer vision solutions for automated applause detection and audience engagement analysis. This cutting-edge system utilizes mobile camera technology to analyze crowd dynamics, emotional responses, and participation levels during live events, presentations, and performances. Advanced algorithms process visual cues including hand movements, facial expressions, and body language to quantify audience enthusiasm and engagement metrics. The system provides real-time feedback to performers and event organizers, enabling dynamic content adjustment based on audience response. Machine learning models trained on diverse demographic groups ensure accurate detection across different cultural contexts and age groups. Applications extend beyond entertainment to include corporate presentations, educational seminars, and public speaking events. The mobile deployment capability allows for flexible setup in various venues, from intimate conference rooms to large auditoriums, providing valuable insights for speakers and event planners.".to_string()
    );

    content_map.insert(3,
        "Our Paint Pinhole Detection capability revolutionizes quality control in automotive and industrial coating applications. This advanced system combines computer vision with AI-powered defect recognition to identify microscopic pinholes, bubbles, and surface irregularities in painted surfaces that are invisible to the naked eye. The technology analyzes surface reflectivity patterns, color consistency, and texture variations across large painted areas with unprecedented precision. Real-time processing enables immediate correction during the painting process, reducing waste and rework costs significantly. The mobile platform allows for in-field inspection of large structures like wind turbine blades, aircraft fuselages, and industrial equipment. Machine learning algorithms continuously improve detection accuracy by learning from validated defect samples. Integration with robotic painting systems enables automated quality feedback loops, ensuring consistent coating quality across production runs while maintaining optimal paint thickness and coverage uniformity.".to_string()
    );

    content_map.insert(4,
        "The Laminate Quality Control project addresses critical inspection needs in composite manufacturing and aerospace applications. Our sophisticated system employs computer vision and AI detection to identify delamination, fiber misalignment, void formation, and resin distribution irregularities in carbon fiber and fiberglass composites. Advanced imaging techniques reveal subsurface defects that traditional inspection methods often miss, ensuring structural integrity in safety-critical applications. The mobile deployment capability enables on-site inspection of large composite structures including aircraft wings, wind turbine blades, and automotive body panels. Real-time analysis provides immediate feedback to manufacturing teams, reducing cycle times and material waste. Machine learning algorithms trained on extensive composite defect databases can predict failure modes and recommend corrective actions. The system integrates seamlessly with existing production workflows, providing detailed inspection reports and statistical quality control data for regulatory compliance and continuous process improvement initiatives.".to_string()
    );

    content_map.insert(5,
        "Our Assembly Validation capability transforms complex manufacturing quality assurance through intelligent computer vision and AI-powered defect detection. This comprehensive system analyzes component positioning, fastener integrity, alignment accuracy, and assembly completeness across diverse manufacturing sectors. Advanced algorithms can detect missing components, incorrect orientations, improper fits, and dimensional variations that could compromise product performance and safety. The mobile platform enables flexible deployment across production lines, from automotive assembly to electronics manufacturing. Real-time processing provides immediate feedback to assembly workers, reducing error rates and rework requirements significantly. Machine learning models continuously adapt to new assembly configurations and quality standards, ensuring consistent performance across varied product lines. Integration capabilities include connection to existing MES systems, providing comprehensive traceability and statistical process control data. The system supports both automated and manual assembly operations, enhancing quality assurance protocols while maintaining production efficiency and reducing overall manufacturing costs.".to_string()
    );

    content_map.insert(6,
        "The Titomic Gun project represents cutting-edge innovation in additive manufacturing quality control and spatial awareness technology. Utilizing HoloLens-based augmented reality combined with advanced computer vision, this system provides real-time monitoring and control of the Titomic Kinetic Fusion process. The technology analyzes particle velocity, temperature distribution, and deposition patterns during the cold spray additive manufacturing process, ensuring optimal material bonding and structural integrity. Spatial awareness algorithms track the exact position and orientation of the spray gun relative to the substrate, enabling precise control of coating thickness and surface coverage. The AR interface provides operators with real-time visual feedback, displaying process parameters, quality metrics, and deviation alerts directly in their field of view. This innovative approach significantly improves manufacturing consistency while reducing training requirements for operators. The system's ability to work in harsh industrial environments makes it ideal for aerospace, defense, and heavy industry applications where precision and reliability are paramount.".to_string()
    );

    content_map.insert(7,
        "Our PCB Missing Components detection system revolutionizes electronics manufacturing quality control through high-precision computer vision and AI-powered component recognition. Utilizing DSLR cameras with specialized zoom lenses, the system can identify missing, misplaced, or incorrectly oriented components on populated circuit boards with exceptional accuracy. Advanced algorithms analyze component shapes, sizes, colors, and markings to verify proper placement against design specifications. The augmented reality interface provides technicians with real-time visual feedback, highlighting discrepancies and providing corrective guidance directly on the PCB surface. Machine learning models trained on extensive component libraries can recognize new components and adapt to design changes automatically. The system processes high-resolution images rapidly, enabling integration into high-speed production lines without compromising throughput. Applications extend from simple consumer electronics to complex aerospace and medical device manufacturing, where component accuracy is critical for safety and reliability. Detailed inspection reports support traceability requirements and continuous improvement initiatives.".to_string()
    );

    content_map.insert(8,
        "The IR Thermal Imaging capability combines infrared sensing with advanced computer vision and AI detection to identify thermal anomalies, energy inefficiencies, and potential equipment failures across diverse industrial applications. This sophisticated system analyzes temperature distribution patterns, heat transfer characteristics, and thermal gradients to detect problems before they become critical failures. The DSLR camera integration enables high-resolution thermal mapping of large structures including solar panels, electrical systems, and mechanical equipment. Augmented reality overlays provide technicians with real-time thermal data visualization, highlighting hot spots and temperature variations directly in their field of view. Machine learning algorithms can predict equipment failure patterns based on thermal signatures, enabling proactive maintenance strategies that reduce downtime and repair costs. Applications span from building energy audits to industrial process monitoring, power grid inspection, and renewable energy system optimization. The mobile deployment capability ensures flexibility across various inspection scenarios while maintaining consistent accuracy and reliability standards.".to_string()
    );

    content_map.insert(9,
        "Our Telescope Antennas project delivers precision alignment and maintenance solutions for radio astronomy and satellite communication systems. This advanced system combines computer vision with augmented reality and spatial awareness technology to ensure optimal antenna positioning and surface accuracy. High-resolution DSLR cameras with specialized zoom lenses capture detailed imagery of antenna surfaces, detecting deformation, surface irregularities, and alignment issues that could affect signal quality. The spatial awareness system provides precise positioning data, enabling accurate tracking of celestial objects and maintaining optimal signal reception. Augmented reality interfaces assist technicians with maintenance procedures, displaying alignment guides, adjustment instructions, and real-time feedback directly on the antenna structure. The system can detect sub-millimeter surface deviations that significantly impact performance at high frequencies. Applications include radio telescopes, satellite ground stations, and deep space communication arrays. The comprehensive solution reduces maintenance time while improving antenna performance and operational reliability, ensuring optimal scientific data collection and communication capabilities.".to_string()
    );

    content_map.insert(10,
        "The Construction Site Tracking project revolutionizes project management and safety monitoring through comprehensive computer vision, AI detection, and spatial awareness technologies. This innovative system monitors construction progress, equipment utilization, worker safety compliance, and material management across large construction sites. Advanced algorithms analyze aerial and ground-level imagery to track building progress, identify potential safety hazards, and optimize resource allocation. The spatial awareness component provides accurate positioning of equipment, materials, and personnel, enabling real-time project coordination and safety monitoring. DSLR cameras capture high-resolution imagery for detailed progress documentation and quality control verification. AI-powered detection systems can identify safety violations, unauthorized personnel, and equipment malfunctions before they become serious incidents. Real-time dashboards provide project managers with comprehensive oversight capabilities, including progress metrics, resource utilization, and safety statistics. The system integrates with existing project management software, providing seamless data flow and automated reporting capabilities that improve project efficiency and safety outcomes.".to_string()
    );

    content_map.insert(11,
        "The Blade MRO (Nahuel) project represents the pinnacle of precision inspection technology for wind turbine blade maintenance, repair, and overhaul operations. Utilizing ultra-high-resolution DSLR cameras with specialized zoom lenses, this system can detect microscopic cracks, delamination, and surface defects that could lead to catastrophic blade failure. The computer vision algorithms analyze surface topology, material consistency, and structural integrity across the entire blade surface, identifying potential failure points before they become critical. AI-powered detection systems trained on extensive blade defect databases can classify damage types and recommend appropriate repair procedures. Augmented reality interfaces provide technicians with detailed inspection guidance and real-time defect visualization during maintenance operations. The system's exceptional precision capabilities enable detection of defects at the 0.1mm level, crucial for identifying early-stage damage in composite blade structures. Integration with maintenance management systems provides comprehensive inspection records, predictive maintenance recommendations, and regulatory compliance documentation for the aerospace maintenance sector.".to_string()
    );

    content_map.insert(12,
        "The BSI (Borescope Inspection) project combines computer vision, AI detection, augmented reality, and large language models to revolutionize internal component inspection and analysis. This comprehensive system enables detailed examination of internal engine components, pipeline interiors, and confined spaces that are inaccessible through traditional inspection methods. Advanced imaging algorithms process borescope video feeds to identify corrosion, wear patterns, foreign object damage, and structural anomalies. The LLM component provides intelligent analysis and natural language reporting of inspection findings, generating detailed technical reports and maintenance recommendations. Augmented reality overlays assist inspectors with navigation guidance, measurement tools, and real-time defect highlighting during inspection procedures. Machine learning models trained on extensive inspection databases can predict component remaining useful life and recommend optimal maintenance intervals. High-zoom lens capabilities enable detailed examination of small components and surface features. The system supports various borescope configurations and integrates with existing maintenance management systems, providing comprehensive inspection documentation and predictive analytics for industrial and aerospace applications.".to_string()
    );

    content_map.insert(13,
        "The NDT UT (Non-Destructive Testing Ultrasonic) project integrates computer vision with augmented reality and spatial awareness to enhance ultrasonic inspection capabilities for critical component evaluation. This innovative system combines traditional ultrasonic testing with advanced visualization and spatial positioning technology to improve inspection accuracy and efficiency. The HoloLens-based interface provides technicians with real-time ultrasonic data visualization, displaying thickness measurements, flaw indications, and material property maps directly overlaid on the inspection surface. Spatial awareness algorithms ensure precise probe positioning and consistent inspection coverage across complex geometries. Computer vision systems analyze ultrasonic waveforms and C-scan images to automatically detect and classify defects including cracks, voids, and inclusions. The augmented reality interface guides inspectors through standardized procedures, ensuring consistent inspection quality and regulatory compliance. Machine learning algorithms can predict component remaining useful life based on defect characteristics and growth patterns. Applications span aerospace, oil and gas, power generation, and manufacturing sectors where structural integrity is paramount for safety and reliability.".to_string()
    );

    content_map.insert(14,
        "Our Indoor Inspection and Marking system with contextual data revolutionizes facility maintenance and quality assurance through advanced augmented reality and spatial awareness technologies. This comprehensive platform enables real-time inspection documentation, defect marking, and contextual information overlay directly onto physical infrastructure. The mobile-based system provides technicians with intuitive interfaces for capturing inspection data, annotating findings, and accessing historical maintenance records. Spatial awareness capabilities ensure accurate positioning of inspection points and defect locations for precise tracking and follow-up actions. The augmented reality interface displays contextual information including component specifications, maintenance history, and repair procedures directly in the technician's field of view. Advanced data integration capabilities connect with existing CMMS and ERP systems, providing seamless workflow integration and automated reporting. The system supports various inspection protocols including safety checks, quality audits, and preventive maintenance procedures. Real-time collaboration features enable remote expert support and immediate supervisor consultation during critical inspections, significantly improving inspection quality and operational efficiency.".to_string()
    );

    content_map.insert(15,
        "The Outdoor Airfield Inspection and Marking system addresses the unique challenges of aviation infrastructure maintenance through robust augmented reality and spatial awareness technologies. This specialized platform enables comprehensive runway, taxiway, and apron inspections while providing real-time defect marking and documentation capabilities. The mobile-based system withstands harsh outdoor conditions while delivering precise GPS-enabled positioning for accurate defect location tracking. Augmented reality interfaces display critical information including pavement specifications, load ratings, and maintenance schedules directly overlaid on the airfield surface. The system can detect and classify various pavement distresses including cracking, rutting, and foreign object debris that could compromise aircraft safety. Spatial awareness algorithms ensure comprehensive coverage during systematic inspections and maintain consistent data quality across multiple inspection teams. Integration with airport management systems provides automated compliance reporting and maintenance scheduling capabilities. The platform supports both routine inspections and emergency response procedures, enabling rapid assessment of airfield conditions following severe weather events or incidents that could affect operational safety.".to_string()
    );

    content_map.insert(16,
        "Our Exhibition capability showcases cutting-edge augmented reality technology for immersive demonstration and marketing applications. This innovative platform creates engaging interactive experiences that captivate audiences and effectively communicate complex technical concepts through visual storytelling. The HoloLens-based system enables visitors to experience virtual product demonstrations, technical simulations, and educational content in three-dimensional space. Advanced rendering algorithms ensure smooth visual performance and realistic object interactions that enhance user engagement and learning outcomes. The system supports multi-user experiences, allowing collaborative exploration and group presentations that facilitate knowledge sharing and team building. Customizable content libraries enable rapid deployment across different exhibition themes and target audiences, from technical trade shows to educational outreach programs. Real-time analytics provide valuable insights into visitor engagement patterns, content effectiveness, and demographic preferences that inform future exhibition strategies. The portable deployment capability ensures flexibility across various venue types while maintaining consistent performance and visual quality that leaves lasting impressions on visitors.".to_string()
    );

    content_map.insert(17,
        "The VR Training project transforms traditional education and skill development through immersive augmented reality and spatial awareness technologies. This comprehensive training platform creates realistic simulations of complex procedures, hazardous environments, and specialized equipment operation without physical risks or resource constraints. The HoloLens-based system provides trainees with hands-on experience in safe virtual environments that closely replicate real-world conditions and challenges. Spatial awareness algorithms track user movements and interactions, providing real-time feedback and performance evaluation throughout training sessions. Advanced simulation engines can recreate various scenarios including emergency procedures, maintenance tasks, and safety protocols with exceptional realism and detail. The system adapts to individual learning styles and progress rates, providing personalized instruction and remedial training where needed. Comprehensive assessment tools track performance metrics, skill development, and competency achievement for certification and compliance purposes. Multi-user capabilities enable team training exercises and collaborative learning experiences that enhance communication and coordination skills essential for complex industrial operations.".to_string()
    );

    content_map.insert(18,
        "The SPECTOR project represents our flagship augmented reality and spatial awareness platform for industrial inspection and maintenance applications. This comprehensive system transforms traditional inspection workflows through immersive visualization, intelligent guidance, and real-time data integration capabilities. The HoloLens-based interface provides inspectors with contextual information overlays, defect highlighting, and step-by-step procedure guidance directly in their field of view. Spatial awareness algorithms ensure precise positioning of inspection points and accurate documentation of findings for reliable tracking and follow-up actions. The system integrates seamlessly with existing enterprise systems, providing automated reporting, work order generation, and compliance documentation. Advanced analytics capabilities analyze inspection trends, predict maintenance requirements, and optimize resource allocation across facility operations. The platform supports various inspection types including safety audits, quality checks, and preventive maintenance procedures across multiple industries. Real-time collaboration features enable remote expert support and immediate supervisor consultation during critical inspections, significantly improving inspection quality, operational efficiency, and safety outcomes while reducing overall maintenance costs.".to_string()
    );

    content_map
}
